FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y build-essential wget libfontconfig1 perl \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*; \
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz; \
    mkdir /install-tl-unx; \
    tar -xvf install-tl-unx.tar.gz -C /install-tl-unx --strip-components=1; \
    rm install-tl-unx.tar.gz

ENV HOME /data

WORKDIR /data

VOLUME ["/data"]
